/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtmosphereBackground: typeof import('./src/components/ui/AtmosphereBackground.vue')['default']
    CountUp: typeof import('./src/components/ui/CountUp.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MarqueeRow: typeof import('./src/components/ui/MarqueeRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeading: typeof import('./src/components/ui/SectionHeading.vue')['default']
  }
}
